# Generated by Django 3.2.9 on 2021-11-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('imageurl', models.CharField(max_length=200, null=True)),
                ('desription', models.CharField(max_length=200, null=True)),
                ('created_at', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
