# Generated by Django 3.2.9 on 2021-11-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_movie_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('movie', 'Movies'), ('series', 'Series')], max_length=200, null=True),
        ),
    ]
