# Generated by Django 3.2.9 on 2021-11-27 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211127_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serverlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serverurl', models.CharField(max_length=200, null=True)),
                ('resolution', models.CharField(max_length=200, null=True)),
                ('size', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.movie')),
            ],
        ),
    ]
