# Generated by Django 3.2.9 on 2021-11-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_serverlink_servername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlink',
            name='serverName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
