# Generated by Django 3.2.9 on 2021-11-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20211128_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profilePic',
            field=models.ImageField(blank=True, upload_to='static/accounts/profiles'),
        ),
    ]
