# Generated by Django 3.2.9 on 2021-11-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_favorite_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
