# Generated by Django 3.2.9 on 2021-11-25 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211125_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkUrl', models.CharField(max_length=200, null=True)),
                ('moviename', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.movie')),
            ],
        ),
    ]
